services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    networks:
      - ezmicroservices

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - ezmicroservices

  configserver:
    image: openjdk:17-alpine
    container_name: configserver
    volumes:
      - ./../configserver/target/configserver-0.0.1-SNAPSHOT.jar:/app.jar
    command: [ "java", "-jar", "/app.jar" ]
    ports:
      - "8071:8071"
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:8071/actuator/health/readiness || exit 1"
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - ezmicroservices

  accounts:
    image: openjdk:17-alpine
    container_name: accounts
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    volumes:
      - ./../accounts/target/accounts-0.0.1-SNAPSHOT.jar:/app.jar
    command: [ "java", "-jar", "/app.jar" ]
    ports:
      - "8080:8080"
    networks:
      - ezmicroservices
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  loans:
    image: openjdk:17-alpine
    container_name: loans
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    volumes:
      - ./../loans/target/loans-0.0.1-SNAPSHOT.jar:/app.jar
    command: [ "java", "-jar", "/app.jar" ]
    ports:
      - "8081:8080"
    networks:
      - ezmicroservices
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  eurekaserver:
    image: openjdk:17-alpine
    volumes:
      - ./../eurekaserver/target/eurekaserver-0.0.1-SNAPSHOT.jar:/app.jar
    container_name: eurekaserver-ms
    command: [ "java", "-jar", "/app.jar" ]
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "wget --quiet --tries=1 --spider localhost:8070/actuator/health/readiness || exit 1"
#      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - ezmicroservices

networks:
  ezmicroservices:
    driver: "bridge"